# Generated by Django 3.2 on 2021-04-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210408_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wlist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.wlist'),
            preserve_default=False,
        ),
    ]
