# Generated by Django 3.2 on 2021-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_wlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlist',
            name='symbol',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
