# Generated by Django 3.2 on 2021-04-19 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_wlist_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wlist',
            name='user',
        ),
        migrations.AddField(
            model_name='wlist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
