# Generated by Django 3.2 on 2021-04-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_account_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wlist',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='entry',
            new_name='entryprice',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='exit',
            new_name='exitprice',
        ),
    ]
